### ISSUE TITLE
Potential Bug in `estimateCrossDomainMessageFee` Calculation

### ISSUE THREAD

**Issue by deseti** [scroll-tech/scroll-contracts#43]
## Problem
This function `testEstimateCrossDomainMessageFee `does not take into account the ( `intrinsicgasfee `) when calculating the cross-domain message cost

## Solution
To fix this bug, the function `testEstimateCrossDomainMessageFee` must take into account the intrinsic gas cost. This can be done by adding the `intrinsicGasFee` value to the cross-domain message cost calculation result

## Implementation Example

```solidity
function testEstimateCrossDomainMessageFee(uint256 baseFee, uint256 gasLimit) external {
    gasLimit = bound(gasLimit, 0, 3000000);
    baseFee = bound(baseFee, 0, 1000000000);

    // Calculate intrinsic gas costs
    uint256 intrinsicGasFee = oracle.calculateIntrinsicGasFee(hex"00");

    // Check if intrinsic gas costs have been calculated
    assertEq(oracle.estimateCrossDomainMessageFee(gasLimit), intrinsicGasFee);

    oracle.setL2BaseFee(baseFee);
    // Add intrinsic gas costs to the calculation result
    assertEq(oracle.estimateCrossDomainMessageFee(gasLimit), baseFee * gasLimit + intrinsicGasFee);
}
``` 

## source
https://github.com/scroll-tech/scroll-contracts/blob/main/src/test/L2GasPriceOracle.t.sol

**Comment by zimpha** [comment]
intrinsic gas is included in the `gasLimit`. @deseti 
for reference: https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L402

**Comment by zimpha** [comment]
we make sure `gasLimit` is greater than or equal to intrinsic gas [here](https://github.com/scroll-tech/scroll-contracts/blob/main/src/L1/rollup/L1MessageQueue.sol#L481).
