### ISSUE TITLE
High Mocha Timeout & Optimizer Settings Concerns

### ISSUE THREAD

**Issue by rychrr** [scroll-tech/scroll-contracts#47]
I noticed a potential performance issue with the Mocha timeout and optimizer settings for code [HERE](https://github.com/scroll-tech/scroll-contracts/blob/2ac4f3f7e090d7127db4b13b3627cb3ce2d762bc/hardhat.config.ts )

**Mocha timeout** 
> In the mocha configuration, the timeout value is extremely large (10000000 ms = ~2.78 hours). This seems excessive and could result in unintended long test durations.

**Optimizer Settings:**
The optimizer field is assigned as:
```
optimizer: {
  enabled: foundry.default?.optimizer || true,
  runs: foundry.default?.optimizer_runs || 200,
},

```
This line will always enable the optimizer because || true will force it on even if foundry.default?.optimizer is false. I think a check should be in place before ->  **_foundry.default?.optimizer !== undefined ? foundry.default?.optimizer : true._**

**Comment by remingtony31** [comment]
You're right to point out these potential performance issues in the configuration for Mocha and the optimizer settings. Here's a detailed breakdown of the improvements you can implement:

### 1. **Mocha Timeout Issue:**
   A timeout of `10000000 ms` (~2.78 hours) is excessive for most testing environments. A more reasonable timeout should be chosen based on the complexity of your tests. You can either:

   - **Reduce the Timeout**: Select a more appropriate timeout value. For example, you might want to set it to 10000 ms (10 seconds), or higher depending on the test cases.
   
   Example:
   ```javascript
   timeout: 10000 // 10 seconds
   ```

   - **Adjust Dynamically for Long Tests**: If some tests genuinely require more time, consider dynamically adjusting the timeout for specific test cases, leaving the default timeout lower.

   Example:
   ```javascript
   describe('long-running test', function() {
     this.timeout(60000); // This test gets 60 seconds
     // test implementation here
   });
   ```

### 2. **Optimizer Settings Issue:**
   You correctly identified that the use of `|| true` in `optimizer.enabled` will always enable the optimizer, even if `foundry.default?.optimizer` is set to `false`. This could cause the optimizer to be enabled unintentionally.

   You suggested a fix, and it looks great. The conditional check ensures that if `foundry.default?.optimizer` is explicitly set to `false`, it won't be overridden.

   Here's the corrected version of the optimizer settings:

   ```javascript
   optimizer: {
     enabled: foundry.default?.optimizer !== undefined ? foundry.default.optimizer : true,
     runs: foundry.default?.optimizer_runs || 200,
   },
   ```

   With this change, if `foundry.default?.optimizer` is `undefined`, the optimizer will default to `true`. If `foundry.default?.optimizer` is explicitly set to `false`, the optimizer will stay disabled as expected.

### Summary of Changes:
- **Mocha Timeout**: Reduce the value or adjust for specific tests.
- **Optimizer Settings**: Use `foundry.default?.optimizer !== undefined ? foundry.default.optimizer : true` to ensure a proper check before enabling.

This should result in better test performance and more predictable configuration behavior.
