### ISSUE TITLE
How to deploy smart contract on scroll.

### ISSUE THREAD

**Issue by rv458** [scroll-tech/scroll-contracts#55]
Here's a simple example of a smart contract written in Solidity that you can deploy on Scroll Crypto:

solidity

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract HelloWorld {
    string public message;

    constructor(string memory initMessage) {
        message = initMessage;
    }

    function updateMessage(string memory newMessage) public {
        message = newMessage;
    }
}

This contract includes:

A public variable message that holds a string.

A constructor to initialize the message.

A function updateMessage to change the message.

To deploy this contract using Hardhat, follow these steps:

1. Set Up Hardhat:

bash
npx hardhat

2. Create the Contract File: Create a new file named HelloWorld.sol in the contracts directory and paste the Solidity code above.

3. Compile the Contract:

bash
npx hardhat compile

Deploy the Contract: Create a new script in the scripts directory, for example, deploy.js:

javascript

async function main() {
    const HelloWorld = await ethers.getContractFactory("HelloWorld");
    const hello_world = await HelloWorld.deploy("Hello, Scroll!");
    await hello_world.deployed();
    console.log("HelloWorld deployed to:", hello_world.address);
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});

Run the deployment script:

bash
npx hardhat run scripts/deploy.js --network scroll

Remember to configure Hardhat to connect to Scroll's network in the hardhat.config.js file.

And there you have it—a basic smart contract and the steps to deploy it on Scroll Crypto! Ready to take it for a spin?

**Comment by Vineetkg20** [comment]
Thanks for sharing this! It's great that you're looking into deploying smart contracts on Scroll. To ensure success, I recommend confirming that your **hardhat.config.js** includes the correct Scroll testnet parameters, such as the RPC URL (https://alpha-rpc.scroll.io/) and chain ID (534353). Also, pay attention to gas limits and prices, as they can differ from other networks. Additionally, verify your private key setup with _.env_ to ensure smooth deployment. Lastly, updating to the latest Hardhat and Solidity versions could prevent compatibility issues. Keep up the awesome work!
