### ISSUE TITLE
Undocumented or non-existant predeploy

### ISSUE THREAD

**Issue by RyanRHall** [scroll-tech/scroll-contracts#66]
This codebase contains a predeploy contract, the [L1BlockContainer](https://github.com/scroll-tech/scroll-contracts/blob/main/src/L2/predeploys/L1BlockContainer.sol). But when I look for this predeploy's address on Scroll's public docs, it [seems absent](https://docs.scroll.io/en/developers/scroll-contracts/#l2-predeploys). What happened to this predeploy? Does it exist on Scroll or not? Thank you!!

**Comment by Thegaram** [comment]
Hi @RyanRHall, this was originally planned to be a predeploy (`0x5300000000000000000000000000000000000001`) but we decided not to deploy it as the "trustless L1 block hash relay" feature design was not finalized yet. So it is not deployed on Scroll or Scroll Sepolia, but it is deployed on the L1SLOAD devnet: https://l1sload-blockscout.scroll.io/address/0x5300000000000000000000000000000000000001/transactions#address-tabs.

**Comment by RyanRHall** [comment]
@Thegaram because this is on your S1LOAD devnet, can I assume you plan to include this predeploy in a future release for mainnet and testnet?
